### PR TITLE
Small cleanup

### PR DESCRIPTION
**Pull request by JanNash**
image

'Small cleanup' might be one of the biggest lies of our time :D

---

This PR 
- cleans up some messy switch statements
- replaces two `debugPrint()` usages with `fatalError()`
- removes all deprecated stuff
- updates build settings recommended by Xcode
- bumps the iOS deployment target to 14.0
- removes all macOS related stuff

---

There's really not that much code left now:
```
jannash EasyPeasy $ ls
Attribute.swift			DimensionAttribute.swift	PositionAttribute+UIKit.swift
CompoundAttribute.swift		EasyPeasy.swift			PositionAttribute.swift
Constant.swift			Item+UIKit.swift		Priority.swift
Context.swift			Item.swift			ReferenceAttribute.swift
DimensionAttribute+UIKit.swift	Node.swift			UIView+Easy.swift
jannash EasyPeasy $ cloc .
      15 text files.
      15 unique files.
       0 files ignored.

github.com/AlDanial/cloc v 1.86  T=0.02 s (617.6 files/s, 87128.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Swift                           15            318            939            859
-------------------------------------------------------------------------------
SUM:                            15            318            939            859
-------------------------------------------------------------------------------
```

I'm asking myself if, since we're maintaining that ourselves anyway now, it would make sense to 
- either move those files into the app project itself
- or create our own Pod from it, only keeping what we actually need

Personally, I'm currently leaning towards moving the files into the app project, since it would be one repo less to maintain and updating/changing stuff in EasyPeasy would be less of a hassle if we didn't have to update EasyPeasy, then switch to the app repo, then update there.

Wdyt?

### CODE REVIEW

**Comment by JanNash** [comment]
There's really not that much code left now:
```
jannash EasyPeasy $ ls
Attribute.swift			DimensionAttribute.swift	PositionAttribute+UIKit.swift
CompoundAttribute.swift		EasyPeasy.swift			PositionAttribute.swift
Constant.swift			Item+UIKit.swift		Priority.swift
Context.swift			Item.swift			ReferenceAttribute.swift
DimensionAttribute+UIKit.swift	Node.swift			UIView+Easy.swift
jannash EasyPeasy $ cloc .
      15 text files.
      15 unique files.
       0 files ignored.

github.com/AlDanial/cloc v 1.86  T=0.02 s (617.6 files/s, 87128.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Swift                           15            318            939            859
-------------------------------------------------------------------------------
SUM:                            15            318            939            859
-------------------------------------------------------------------------------
```

I'm asking myself if, since we're maintaining that ourselves anyway now, it would make sense to 
- either move those files into the app project itself
- or create our own Pod from it, removing quite some

Wdyt?

**Comment by JanNash** [comment]
Btw, I can also split this up into two PRs, one with the few small refactorings, one all the stuff is deleted.

**Comment by tcwalther** [comment]
I agree. Let's vendor this in our repo. And I'm mostly indifferent about making one or two PRs; I know it's a gigantic one but it's not too hard to review.

**Review by tcwalther — APPROVED** [review]

**Comment by JanNash** [comment]
Then LGTM, I'll copy the stuff over into our repo then.

**Pull request merged**
